"""Init

Revision ID: 5a188c7e9e8f
Revises: 3512b954651e
Create Date: 2022-10-28 12:33:47.635570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a188c7e9e8f'
down_revision = '3512b954651e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
